### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by harden13song** [BobXWu/InfoCTM#1]
你好，我想用您的infoctm模型操作自己的数据集，那么dataset中的npz文件和vocab_cn和en文件应该怎么生成

**Comment by harden13song** [comment]
此问题已解决 我还有一个问题是论文中说用训练的svm来对分类的f1进行测试，请问这部分的代码是否可以发给我，谢谢

**Comment by bobxwu** [comment]
你好，请参考 [topmost](https://github.com/BobXWu/TopMost/blob/main/tutorials/tutorial_crosslingual_topic_models.ipynb) and [gensim.models.Word2Vec](https://radimrehurek.com/gensim/models/word2vec.html).
